import sys
import peppy
import glob

#configfile: "../../config/config.yaml"
configfile: "config/config.yaml"
pepfile: "config/pep.yaml"

SAMPLES = [x.sample_name for x in pep.samples]

configfile: "config/config.yaml"

FRAGLEN = config.get("FRAGLEN", 200),
BINSIZE = config.get("BINSIZE", 50),

SAMPLES = [x.sample_name for x in pep.samples]

CHIPS = [x.sample_name for x in pep.samples if not x.input == ["NA"]]


rule all:
    input:
        #expand("results/csem_mosaics/trimmed/{sample}.fastp.fastq.gz", sample=SAMPLES),
        #expand("results/csem_mosaics/csem-dedup/{sample}.sorted.bam", sample=SAMPLES),
        expand("results/csem_mosaics/mosaics/{s}/{s}.mosaics.rds", s=CHIPS),
        expand("results/csem_mosaics/viz/{s}.log2ratio.bw",s=CHIPS),
        #"results/csem_mosaics/multimapper_stats/csem_multimapper_stats.txt",
        #expand("results/csem_mosaics/viz/{s}.fingerprint.png",s=CHIPS),
        "results/csem_mosaics/misc/pan_te_ranking/all.pan_te_ranking.tsv.gz",
        expand("results/csem_mosaics/motifs/{ms}/{sample}/",ms=["xstreme","sea"], sample=CHIPS),

include: "rules/prep.smk"
include: "rules/align.smk"
include: "rules/csem.smk"
include: "rules/mosaics.smk"
include: "rules/viz.smk"
include: "rules/misc.smk"
include: "rules/motifs.smk"